services:
  app:
    build:
      context: .
      dockerfile: docker/gemm-cuda.Dockerfile
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Keep the docker socket mount if you need it
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
